<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.sap.cloud.sample</groupId>
        <artifactId>password-storage-parent</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <name>Password Storage Sample</name>
    <artifactId>password-storage-sample</artifactId>
    <packaging>war</packaging>

    <description>This sample demonstrates the usage of Password Store so that you can securely persist passwords and key phrases such as passwords for keystore files</description>
    <licenses>
        <license>
            <name>SAP DEVELOPER LICENSE AGREEMENT</name>
            <url>https://tools.hana.ondemand.com/developer-license-3.1.txt</url>
        </license>
    </licenses>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>

        <credential-store-client.version>1.0.0</credential-store-client.version>
        <jakarta.servlet-api.version>6.1.0</jakarta.servlet-api.version>

        <maven-war-plugin.version>3.4.0</maven-war-plugin.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.sap.cloud.sample</groupId>
            <artifactId>credential-store-client</artifactId>
            <version>${credential-store-client.version}</version>
        </dependency>
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <version>${jakarta.servlet-api.version}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>${maven-war-plugin.version}</version>
                <configuration>
                    <warName>${project.artifactId}</warName>
                </configuration>
            </plugin>
        </plugins>
    </build>
    
</project>

