<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.sap.cloud.sample</groupId>
    <artifactId>persistence</artifactId>
    <version>1.0.0</version>
    <packaging>war</packaging>

    <description>This sample provides relational persistence with JDBC.</description>
    <licenses>
        <license>
            <name>SAP DEVELOPER LICENSE AGREEMENT</name>
            <url>https://tools.hana.ondemand.com/developer-license-3.1.txt</url>
        </license>
    </licenses>
    
    <properties>
        <lib.dir.path>${project.basedir}/lib</lib.dir.path>

        <sap.cloud.sdk.version>4.72.6</sap.cloud.sdk.version>
        <sap.security.csi.version>1.0.1</sap.security.csi.version>
        <sap.security.csi.jar>com.sap.security.core.server.csi_${sap.security.csi.version}.jar</sap.security.csi.jar>

        <maven-war-plugin.version>3.4.0</maven-war-plugin.version>
    </properties>

    <dependencies>
        <!-- The SAP BTP Java Web Tomcat 9 API -->
        <dependency>
            <groupId>com.sap.cloud</groupId>
            <artifactId>neo-java-web-api</artifactId>
            <version>${sap.cloud.sdk.version}</version>
            <scope>provided</scope>
        </dependency>
        
        <!-- Required for compilation and required at runtime (additional web application libraries) -->
        <dependency>
            <groupId>com.sap.security.core.server</groupId>
            <artifactId>csi</artifactId>
            <version>${sap.security.csi.version}</version>
            <scope>system</scope>
            <systemPath>${lib.dir.path}/${sap.security.csi.jar}</systemPath>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>${maven-war-plugin.version}</version>
                <configuration>
                    <warName>${project.artifactId}</warName>
                    <webResources>
                        <resource>
                            <directory>${lib.dir.path}</directory>
                            <includes>
                                <include>${sap.security.csi.jar}</include>
                            </includes>
                            <targetPath>WEB-INF/lib</targetPath>
                        </resource>
                    </webResources>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
