<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.sap.cloud.sample</groupId>
    <artifactId>persistence-with-ejb</artifactId>
    <version>1.0.0</version>
    <packaging>war</packaging>

    <description>This sample provides container-managed persistence with EJB.</description>
    <licenses>
        <license>
            <name>SAP DEVELOPER LICENSE AGREEMENT</name>
            <url>https://tools.hana.ondemand.com/developer-license-3_2.txt</url>
        </license>
    </licenses>

    <properties>

        <lib.dir.path>${project.basedir}/src/main/webapp/WEB-INF/lib</lib.dir.path>

        <neo.javaee7.version>1.195.5</neo.javaee7.version>
        <sap.security.csi.version>1.0.1</sap.security.csi.version>
        <sap.security.csi.jar>com.sap.security.core.server.csi_${sap.security.csi.version}.jar</sap.security.csi.jar>
    </properties>

    <dependencies>
        <!-- https://mvnrepository.com/artifact/com.sap.cloud/neo-javaee7-wp-api -->
        <dependency>
            <groupId>com.sap.cloud</groupId>
            <artifactId>neo-javaee7-wp-api</artifactId>
            <version>${neo.javaee7.version}</version>
            <scope>provided</scope>
        </dependency>

        <!-- Required for compilation and required at runtime (additional web application libraries) -->
        <dependency>
            <groupId>com.sap.security.core.server</groupId>
            <artifactId>csi</artifactId>
            <version>1.0.1</version>
            <scope>system</scope>
            <systemPath>${lib.dir.path}/${sap.security.csi.jar}</systemPath>
        </dependency>

        <!-- https://mvnrepository.com/artifact/javax.ejb/ejb-api -->
        <dependency>
            <groupId>javax.ejb</groupId>
            <artifactId>ejb-api</artifactId>
            <version>3.0</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.sap.cloud.db.jdbc</groupId>
            <artifactId>ngdbc</artifactId>
            <version>2.23.10</version>
            <type>pom</type>
        </dependency>
    </dependencies> 

 <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.4.0</version>
                <configuration>
                    <warName>${project.artifactId}</warName>
                    <webResources>
                        <resource>
                            <directory>${lib.dir.path}</directory>
                            <includes>
                                <include>${sap.security.csi.jar}</include>
                            </includes>
                            <targetPath>WEB-INF/lib</targetPath>
                        </resource>
                    </webResources>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
